#pragma once

typedef enum {
	OPEN_FILE_ERROR,
	WSA_STARTUP_ERROR,
	WSA_CLEANUP_ERROR,
	SOCKET_CREATION_ERROR,
	CLOSING_SOCKER_ERROR,
	SET_ADDRESS_ERROR,
	BIND_ERROR,
	LISTENING_ERROR,
	SERVER_CONNECTION_ERROR,
	PLAYER_CONNECTION_ERROR,
	SEND_ERROR,
	INVALID_MESSAGE_BUFFER,
	MALLOC_FAILED,
	RECV_ERROR,
	MUTEX_CREATION_FAIL,
	REALSE_MUTEX_ERROR,
	REALSE_SEMAPHORE_ERROR,
	USERNAME_ALREADY_EXISTS,
	PLAYER_DISCONNECTED,
	SEMAPHORE_CREATION_ERROR,
	WAIT_FOR_SINGLE_OBJECT_ERROR,
	THREAD_CREATION_FAIL
} ErrorCodes;

void PrintError(ErrorCodes error_name, long error_code, int line_number, char* file_name);